coverage:
  precision: 2
  round: down
  range: "75...100"

ignore:
  - "tests/**"
  - "src/prog/**"
  - "src/utility/Logger.cpp"
  - "include/BSMPT/utility/Logger.h"
  - "src/Kfactors/Kfactors.cpp"
  - "src/models/ClassPotentialOrigin_deprecated.cpp"
  - "src/models/ClassTemplate.cpp"
  - "src/WallThickness/WallThickness1D.cpp"
  - "standalone/**"
  - "src/utility/spline/spline.cpp"
  - "src/utility/asciiplotter/asciiplotter.cpp"
  - "example/**"
  - ".github"
  - "**/README.md"
