# SPDX-FileCopyrightText: 2021 Philipp Basler, Margarete Mühlleitner and Jonas Müller
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Benchmark
on:
  push:
    branches: [master]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          persist-credentials: false
    - name : installPackages
      run : sudo apt-get update && sudo apt-get install --no-install-recommends --yes libgsl-dev libeigen3-dev libnlopt-dev libnlopt-cxx-dev libboost-all-dev libbenchmark-dev
    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v2
      id: cpu-cores
    - name: cmake
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: compile
      run: cd build && cmake --build . -j${{ steps.cpu-cores.outputs.count }} --config Release -t benchmarks
    - name: run benchmarks
      run: cd build && ./bin/benchmarks --benchmark_format=json --benchmark_out=benchmark_result.json
    - name: Archive benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark_result
        path: build/benchmark_result.json
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: C++ Benchmark
        tool: 'googlecpp'
        output-file-path: build/benchmark_result.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        benchmark-data-dir-path: "benchmarks"
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '150%'
        comment-on-alert: true
        fail-on-alert: true
