# SPDX-FileCopyrightText: 2021 Philipp Basler, Margarete Mühlleitner and Jonas Müller
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Mac build develop branch

on:
  push:
    branches: [ develop ]
    
jobs:
  build-mac:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    steps:
    - uses: actions/checkout@v4
      with:
          persist-credentials: false
    - name: installPackages
      run: brew install eigen && brew install gsl && brew install nlopt && brew install boost && brew install libomp && brew install nlohmann-json
    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v2
      id: cpu-cores
    - name: cmake
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && cmake --build . -j${{ steps.cpu-cores.outputs.count }}
