# SPDX-FileCopyrightText: 2021 Philipp Basler, Margarete Mühlleitner and Jonas Müller
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Ubuntu build develop branch

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    steps:
    - uses: actions/checkout@v4
      with:
          persist-credentials: false
    - name : installPackages
      run : sudo apt-get install --no-install-recommends --yes libgsl-dev libeigen3-dev libnlopt-dev libnlopt-cxx-dev libboost-all-dev nlohmann-json3-dev
    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v2
      id: cpu-cores
    - name: cmake
      run: mkdir build && cd build && cmake .. 
    - name: make
      run: cd build && cmake --build . -j${{ steps.cpu-cores.outputs.count }}



