name: Check description

on:
  pull_request:
   types: [opened, edited, reopened, synchronize]
     
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }} 
    cancel-in-progress: true
 
jobs:
  print_title_of_pr:
    runs-on: ubuntu-latest
  
    steps:
      - name : Get Body of PR
        env:
            PRBODY: ${{ github.event.pull_request.body }}
        run: echo The body of your PR is $PRBODY
      - name : Deduce bump mode
        run: |
              major=$(echo "$PRBODY" | grep -iE "^\s*-\s*\[x\]\s*Break \(major\)" | wc -l)
              minor=$(echo "$PRBODY" | grep -iE "^\s*-\s*\[x\]\s*Feature \(minor\)" | wc -l)
              patch=$(echo "$PRBODY" | grep -iE "^\s*-\s*\[x\]\s*Bug fix \(patch\)" | wc -l)
              nobump=$(echo "$PRBODY" | grep -iE "^\s*-\s*\[x\]\s*No source changes \(no version change\)" | wc -l)
  
              echo $major
              echo $minor
              echo $patch
              echo $nobump
  
              echo $((major + minor + patch + nobump)) 
  
              if [[ $((major + minor + patch + nobump)) -eq 1 ]]; then
                echo "Exactly one option selected."
              else
                echo "Invalid options selected."
                exit 1
              fi 