name: Check description

on:
  push:
  pull_request:
   types: [opened, synchronize]
     
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }} 
    cancel-in-progress: true
 
jobs:
  print_title_of_pr:
    runs-on: ubuntu-latest
  
    steps:
      - name : Print Body of PR
        env:
            TITLE: ${{ github.event.pull_request.body }}
        run: echo The Title of your PR is $TITLE