name: Run cmake-format linter

on: 
  pull_request:
    branches: [ master, develop ]
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} 
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Format CMake files
      id: cmake-format
      uses: PuneetMatharu/cmake-format-lint-action@v1.0.4
      with:
        args: --config-files .cmake-format.py --in-place

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_user_name: cmake-format-bot
        commit_message: 'Automated commit of cmake-format changes.'